version: "3.8"

networks:
  jenkins_network:
    driver: bridge

services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin_password
    networks:
      - jenkins_network

  react-slave:
    image: jenkins/inbound-agent
    container_name: react-slave
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=react-slave
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=<Replace_with_React_Slave_Secret>
    volumes:
      - react_slave_home:/home/jenkins
    networks:
      - jenkins_network

  springboot-slave:
    image: jenkins/inbound-agent
    container_name: springboot-slave
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=springboot-slave
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=<Replace_with_SpringBoot_Slave_Secret>
    volumes:
      - springboot_slave_home:/home/jenkins
    networks:
      - jenkins_network

volumes:
  jenkins_home:
  react_slave_home:
  springboot_slave_home:
