services:
  jenkins-master:
    build: ./jenkins
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-slave-fe:
    build:
      context: .
      dockerfile: ./jenkins-slave-fe/Dockerfile
    container_name: jenkins-slave-fe
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=slave-fe
      - JENKINS_SECRET=ce7d975857b1168357c501571137c44e8eac8bd331e56ff4a704785d876ed1ce
    privileged: true
    user: root
    entrypoint: ["/usr/local/bin/dockerd-entrypoint.sh"]
    ports:
      - "3000:3000"

  jenkins-slave-be:
    build: ./jenkins-slave-be
    container_name: jenkins-slave-be
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=slave-be
      - JENKINS_SECRET=e3f1669e45795da04f03938585bcfca22e73ba47980c7b617a4e243e832e28a6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  jenkins_home:
