pipeline {
    agent { label 'backend' }
    stages {
        stage('Cleanup') {
            steps {
                script {
                    sh '''
                        docker image prune -f
                        docker container prune -f
                    '''
                }
            }
        }
        
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/Albert333s/jenkins-project.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh '''
                        cd springboot-app
                        docker build -t springboot-app-image .
                    '''
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh '''
                        docker run -d -p 8002:8080 --name springboot-app-container springboot-app-image
                    '''
                }
            }
        }
    }
}
