pipeline {
    agent { label 'backend' }
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/Albert333s/jenkins-project.git', branch: 'main'
            }
        }

        stage('Build Spring Boot App') {
            steps {
                dir('springboot-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Run Spring Boot App') {
            steps {
                dir('springboot-app') {
                    sh '''
                        nohup java -jar target/*.jar > nohup.out 2>&1 &
                        sleep 5
                        cat nohup.out
                    '''
                }
            }
        }
    }
}
