pipeline {
    agent { label 'frontend' }
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/Albert333s/jenkins-project.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Building Docker image
                    sh '''
                        cd react-app
                        docker build -t react-app-image .
                    '''
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Running Docker container and exposing it to port 3000
                    sh '''
                        docker run -d -p 3000:3000 --name react-app-container react-app-image
                    '''
                }
            }
        }
    }
    post {
        always {
            // Cleanup Docker container after build
            sh 'docker stop react-app-container || true && docker rm react-app-container || true'
        }
    }
}
