pipeline {
    agent { label 'frontend' }
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/Albert333s/jenkins-project.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Building Docker image
                    sh '''
                        cd react-app
                        docker build -t react-app-image .
                        echo "Docker image has been built successfully"
                        docker images
                        echo "Docker container"
                        docker ps -a                                       
                    '''
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Remove existing container if it exists
                    sh '''
                        if [ $(docker ps -a -q -f name=react-app-container) ]; then
                            docker rm -f react-app-container
                        fi
                    '''
                    
                    // Running Docker container and exposing it to port 3000
                    sh '''
                        docker run -d -p 3000:3000 --name react-app-container react-app-image
                    '''
                }
            }
        }
    }
    post {
        always {
            // Cleanup Docker container after build
            sh 'docker stop react-app-container || true && docker rm react-app-container || true'
        }
    }
}
